### ISSUE TITLE
Missing TGrid::Connect() on the Grid

### ISSUE THREAD

**Issue by dberzano** [alisw/AliDPG#153]
As reported by @catalinristea, all AliDPG versions containing #134 are missing, in some cases, the proper `TGrid::Connect()` where required.

This affects all versions **from v5-09-XX-46 (included) on**.

As a result, some Grid jobs are still running with older AliDPG versions.

@catalinristea: would you be able to provide us with more details (type of job: MC or Reco? logs of failing jobs?) in order for us to fix it?

Thanks!

**Comment by catalinristea** [comment]
Ciao Dario,

Previously I have fixed CPass0 merging+OCDB for RAW data reconstruction starting with AliDPG v5-09-XX-48. Affected versions were v5-09-XX-46 and 47.
The fix is this one https://github.com/alisw/AliDPG/commit/b6c95b365af4f5832692cfcd35faa407521f3127 and https://alice.its.cern.ch/jira/browse/ALIROOT-7885 contains the link to JDL to reproduce the error.
Please let me know if I can further help.
Thanks!

Yours,
Catalin.

**Comment by catalinristea** [comment]
Hi Dario,

No need to be worried about the fix above, the reco runs fine in GRID and since RelVal uses master, it's fine also there. Thanks!

Yours,
Catalin.

**Comment by dberzano** [comment]
Thanks for clarifying! The issue is solved then.
